### ISSUE TITLE
Social media: Replace words with icons

### ISSUE THREAD

**Issue by vns2** [janastu/ncbs-modular#113]
Replace twitter, facebook, google+ with standard F, bird, + icons for the three.

**Comment by Madhuvanthi-A** [comment]
this upgrade is pending and lined up for 1.0.2 
Aaccording to Thara's suggestion we won't use icons, as already there are to many icons to load and the color schemes of the social icons wont go well with the design.

**Comment by salus-sage** [comment]
icons awaited from Thara, suggestion for having icons with text

**Comment by salus-sage** [comment]
This upgrade is failing to recognize img url, some weird bug, will need to check

**Comment by vns2** [comment]
I don't think we need the text 'Twitter' and 'Facebook' as seen in this solution. Just their icons are sufficient, no?

![social_media_icon](https://user-images.githubusercontent.com/4581081/39224909-2b326c10-4867-11e8-84d3-babe78e886b2.png)

**Comment by salus-sage** [comment]
this will be pushed shortly
