### ISSUE TITLE
Switching from full page to 'tablet/phone' view: Change screen size when this triggers

### ISSUE THREAD

**Issue by vns2** [janastu/ncbs-modular#114]
Right now, it seems like if the desktop screen shows only if size is > 13"? At ~12" (maybe different number), it switches to attached image layout, which looks weird. And then, upon going smaller, it switches to phone/tablet layout. Can this be changed such that we have the full desktop layout even in tablet, and only have to switch to phone layout in screen width 5" or less? This might be possible if we have icons for social media, and so can get more content with smaller width.
 
![screensize2](https://user-images.githubusercontent.com/4581081/29059760-a3fb31d6-7c34-11e7-86ce-0a088dc1f611.png)

![screensize](https://user-images.githubusercontent.com/4581081/29059683-5d3994c2-7c34-11e7-90c4-32be0c50cc5f.png)

**Comment by Madhuvanthi-A** [comment]
design issue, will consult with Thara.
