### ISSUE TITLE
Peopleplex: Redundant data + auto play of audio to be stopped 

### ISSUE THREAD

**Issue by vns2** [janastu/ncbs-modular#118]
1) When you hover on a node in Peopleplex, you get the name, designation, affiliation data pop up twice. I am not sure what is going on. But it should only come once. 

2) The auto play of the audio should be stopped, I think? 
![peopleplex](https://user-images.githubusercontent.com/4581081/29064554-f3158af2-7c46-11e7-80bc-3c52f5b5ed73.png)

**Comment by Madhuvanthi-A** [comment]
known bug, pipelined for 1.0.3

**Comment by salus-sage** [comment]
stopped autoplay for hover, however still kept it for click
