### ISSUE TITLE
Gallery: Should only open upon click

### ISSUE THREAD

**Issue by vns2** [janastu/ncbs-modular#123]
Sometimes gallery seems to auto-open or be open at end of chapter. It should only open upon clicking green button.

**Comment by Madhuvanthi-A** [comment]
solution: add class collapse to div gallery

**Comment by salus-sage** [comment]
gallery commits d41bf25db050c861f09fd4ff562b5db98fe4e810

**Comment by salus-sage** [comment]
image gallery is updated with click to open, pending video and sound gallery will be handled in issue #142 and #150
