### ISSUE TITLE
Gallery: Bucket stuff inside by category

### ISSUE THREAD

**Issue by vns2** [janastu/ncbs-modular#124]
Dont know what we decided. But I think content needs to have more structure to it. 

Suggestion: You have equal sized (say, one-inch box) tiles inside gallery, with cover title saying 'image', 'video' or 'audio'. When you hover over tile, it switches to actual content thumbnail. You click on thumbnail, and it opens up lightbox with content.

**Comment by salus-sage** [comment]
related to issue #141  and #142
