### ISSUE TITLE
Opening 'waiting' image of floating dandelion

### ISSUE THREAD

**Issue by vns2** [janastu/ncbs-modular#126]
Like this. 

But I suggest that in the loading frame, there is no horizontal line for the menu that shows up. It is just dandelions.

**Comment by Madhuvanthi-A** [comment]
Thara will b consulted for this, the floating dandelion illustration is not going to be there. we were just testing.

**Comment by vns2** [comment]
The floating dandelion seems like a nice intro to the page. I'd say stick with it. Just don't have the thick horizontal line, and try and do a fade out from floating dandelion to homepage when it is loaded (right now, it's sudden).

**Comment by salus-sage** [comment]
revised floating dandellion illustration is awaited from Thara

**Comment by salus-sage** [comment]
related to issue #158 probably not a good idea to use a loading substitute.
