### ISSUE TITLE
Mobile design: Tabs for chapters to be aligned

### ISSUE THREAD

**Issue by vns2** [janastu/ncbs-modular#129]
When looking in small screen size, the tabs for the chapters are not aligned. See image. Maybe the chapter headings can come as a menu bar, one below the other? Or if simpler, have one chapter per line.

![mobilesize](https://user-images.githubusercontent.com/4581081/29065282-404ef982-7c49-11e7-8c6f-27cee0810d62.png)

**Comment by Madhuvanthi-A** [comment]
Design issue, need to consult Thara

**Comment by salus-sage** [comment]
Thara suggests it looks good without alignment, hence marking wontfix on this one
