### ISSUE TITLE
Content Testing: Test for content in each page

### ISSUE THREAD

**Issue by salus-sage** [janastu/ncbs-modular#13]
Test cases:
Do CTRL+F in browser and look for "Loading"
Inspect element and find the data-tag of the element and document in this issue.

**Comment by Madhuvanthi-A** [comment]
identity page :
	videos :-1: 
		space-for-biology : 1-Space-V1
		science-in-india  : 1-India-V1
		recognition       : 1-Recognition-V1

institution building page :
	video :-	
		space-and-autonomy : 2-Autonomy-V1

	image	:-		
		paper-trails	   : 2-Paper-P1
		architecture	   : 2-Arch-P1

	slide	:-
		architecture	   :             2-Arch-PS4
							 2-Arch-PS1
							 2-Paper-PS2
							 2-Arch-PS2

growth page :
	audio :-
		collaborations	   :             3-Collab-A2
							 3-Collab-A4
							 3-Collab-A5
	video :-		
		hiring			   : 3-Hiring-V1
		start-ups 		           : 3-Startup-V1
		collaborations	           : 3-Collab-V1
		student-selections      : 3-Student-V1

	image	:-
		
		hiring			   : 3-Hiring-P1
		start-ups 		           : 3-Startup-P1
		collaborations	           : 3-Collab-P1
		student-selections      : 3-Students-P1
		scaling			   : 3-Scaling-P1

	slide	:-		
		collaborations	   :             3-Collab-PS2
							 3-Collab-PS1( need to change audio to slide in data-component)

research page :
	audio :-
		curatorial-note	    :
		applied-toggle		:        4-Toggle-A3
							  4-Toggle-A1
							  4-Toggle-A2
							  4-Toggle-A4
							  4-Toggle-A5
		area-shifts			: 4-Shifts-A1
							  4-Shifts-A0
							  4-Shifts-A3
							  4-Shifts-A4
							  4-Shifts-A2 
		queries-and-tools	:         4-Tool-A1
							  4-Tool-A5
							  4-Tool-A3
							  4-Tool-A2
							  4-Tool-A4		

	video :-
		
		applied-toggle		        : 4-Toggle-V1
		area-shifts			: 4-Shifts-V1
		queries-and-tools	        : 4-Tools-V1

	image	:-
		area-shifts			: 4-Shifts-P1
		queries-and-tools	        : 4-Tool-P1

	slide	:-	
		applied-toggle		        : 4-Toggle-PS2
							  4-Toggle-PS1
		area-shifts			: 4-Shifts-PS4
							  4-Shifts-PS1
							  4-Shifts-PS2
		queries-and-tools	       : 4-Tool-PS1
							  4-Tool-PS2

education page :
	audio :-
		
		building-knowledge        : 5-Knowledge-A3
		mentorship    	               : 5-Mentors-A1
							 5-Mentors-A4
							 5-Mentors-A2
							 5-Mentors-A0
							 5-Mentors-A5
							 5-Mentors-A3	
	videos :-
		
		building-knowledge        : 5-Knowledge-V1
		mentorship    	               : 5-Mentors-V1

	image	:-
		
		building-knowledge        : 5-Knowledge-P1
		mentorship    	               : 5-Mentor-P1

	slide	:-
		
		building-knowledge    :     5-Knowledge-PS1
							 5-Knowledge-PS4
							 5-Knowledge-PS2
		mentorship    	       :        5-Mentor-PS4
							 5-Mentors-PS1
	
ripple-effect page :
	audio :-	
		effect-and-toll	              :          6-Effect-Toll-A1
								 6-Effect-Toll-A2
								 6-Effect-Toll-A0
								 6-Effect-Toll-A3
								 6-Effect-Toll-A4
								 6-Effect-Toll-A5
	image	:-	
		effect-and-toll	       : 6-Effect-Toll-P1
		intersection-isolation : 6-Isolation-P1

	slide	:-	
		effect-and-toll	               :        6-Effect-Toll-PS1
								 6-Effect-Toll-PS4
								 6-Effect-Toll-PS2

intersections page : 
	audio :-
		gender-eqality	          :     7-Gender-A3
							 7-Gender-A2
							 7-Gender-A0
		heirarchy-&-class        :    7-Hierarchy-A1
							 7-Hierarchy-A2
							 7-Hierarchy-A3
							 7-Hierarchy-A4
							 7-Hierarchy-A5

		NCBS-community	   :     7-NCBS Community-A1
							 7-NCBS Community-A4
							 7-NCBS Community-A2
							 7-NCBS Community-A3
	video :-
		outside-world      : 7-Outside-V1

	image	:-	
		gender-eqality	   : 7-Gender-P1
		heirarchy-&-class  : 7-Hierarchy-P1
		NCBS-community	   : 7-NCBS-P1

	slide	:-
		gender-eqality	   :             7-Gender-PS2
							 7-Gender-PS1
							 7-Gender-PS4
		heirarchy-&-class  :          7-Hierarchy-PS1
		NCBS-community	   :    7-NCBS-PS1
							 7-NCBS-PS2

**Comment by Madhuvanthi-A** [comment]
identity page :
	videos :-
space-for-biology : 1-Space-V1
science-in-india  : 1-India-V1
recognition       : 1-Recognition-V1

institution building page :
video :-	
space-and-autonomy : 2-Autonomy-V1

image :-		
paper-trails : 2-Paper-P1
architecture : 2-Arch-P1

slide	:-
architecture : 2-Arch-PS4
2-Arch-PS1
2-Paper-PS2
 2-Arch-PS2

growth page :
audio :-
collaborations:  3-Collab-A2
3-Collab-A4
 3-Collab-A5

video :-		
hiring: 3-Hiring-V1
start-ups : 3-Startup-V1
collaborations: 3-Collab-V1
student-selections : 3-Student-V1

image:-		
hiring			   : 3-Hiring-P1
start-ups 		           : 3-Startup-P1
collaborations	           : 3-Collab-P1
student-selections      : 3-Students-P1
scaling			   : 3-Scaling-P1

slide	:-		
collaborations	   :    3-Collab-PS2
3-Collab-PS1( need to change audio to slide in data-component)

research page :
audio :- 
applied-toggle	:  4-Toggle-A3
4-Toggle-A1
4-Toggle-A2
4-Toggle-A4
 4-Toggle-A5
area-shifts: 4-Shifts-A1
4-Shifts-A0
4-Shifts-A3
4-Shifts-A4
 4-Shifts-A2 
queries-and-tools	:  4-Tool-A1
4-Tool-A5
4-Tool-A3
4-Tool-A2
4-Tool-A4		

video :-
applied-toggle	 : 4-Toggle-V1
area-shifts: 4-Shifts-V1
queries-and-tools: 4-Tools-V1

image:-
area-shifts: 4-Shifts-P1
queries-and-tools: 4-Tool-P1

slide	:-	
applied-toggle : 4-Toggle-PS2
4-Toggle-PS1
area-shifts: 4-Shifts-PS4
 4-Shifts-PS1
4-Shifts-PS2
queries-and-tools : 4-Tool-PS1
4-Tool-PS2

education page :
audio :-
building-knowledge        : 5-Knowledge-A3
mentorship    	               : 5-Mentors-A1
5-Mentors-A4
5-Mentors-A2
5-Mentors-A0
5-Mentors-A5
5-Mentors-A3	

videos :-
building-knowledge        : 5-Knowledge-V1
mentorship    	               : 5-Mentors-V1

image:-		
building-knowledge  : 5-Knowledge-P1
mentorship  : 5-Mentor-P1

slide	:-
building-knowledge    :     5-Knowledge-PS1
							 5-Knowledge-PS4
							 5-Knowledge-PS2
		mentorship    	       :        5-Mentor-PS4
							 5-Mentors-PS1
	
ripple-effect page :
	audio :-	
		effect-and-toll	              :          6-Effect-Toll-A1
								 6-Effect-Toll-A2
								 6-Effect-Toll-A0
								 6-Effect-Toll-A3
								 6-Effect-Toll-A4
								 6-Effect-Toll-A5

image	:-	
		effect-and-toll	       : 6-Effect-Toll-P1
		intersection-isolation : 6-Isolation-P1

slide	:-	
		effect-and-toll	               :        6-Effect-Toll-PS1
								 6-Effect-Toll-PS4
								 6-Effect-Toll-PS2

intersections page : 
	audio :-
		gender-eqality	          :     7-Gender-A3
							 7-Gender-A2
							 7-Gender-A0
		heirarchy-&-class        :    7-Hierarchy-A1
							 7-Hierarchy-A2
							 7-Hierarchy-A3
							 7-Hierarchy-A4
							 7-Hierarchy-A5

NCBS-community	   :     7-NCBS Community-A1
							 7-NCBS Community-A4
							 7-NCBS Community-A2
							 7-NCBS Community-A3


video :-
		outside-world      : 7-Outside-V1

image	:-	
		gender-eqality	   : 7-Gender-P1
		heirarchy-&-class  : 7-Hierarchy-P1
		NCBS-community	   : 7-NCBS-P1

slide	:-
		gender-eqality	   :             7-Gender-PS2
							 7-Gender-PS1
							 7-Gender-PS4
		heirarchy-&-class  :          7-Hierarchy-PS1
		NCBS-community	   :    7-NCBS-PS1
							 7-NCBS-PS2

**Comment by salus-sage** [comment]
Hi @Madhuvanthi-A , I have resolved most of the issues related to this issue, can we do another round of testing to confirm all problems are resolved. it's very urgent and needs to be done on sunday.

**Comment by Madhuvanthi-A** [comment]
Following are not loading

institution-building
space and autonomy:
2-Autonomy-P1
2-Autonomy-PS4
2-Autonomy-PS2
2-Autonomy-A2
2-Autonomy-PS1
2-Autonomy-A4
2-Autonomy-A3
2-Autonomy-A1

growth
collaborations:
3-Collab-P1
3-Collab-PS2
3-Collab-PS1
3-Collab-A2
3-Collab-A4
3-Collab-A5

research
basic-and-applied-toggle:
4-Toggle-PS2
4-Toggle-A3
4-Toggle-PS1
4-Toggle-A1
4-Toggle-A2
4-Toggle-A4
4-Toggle-A5
areas-and-shifts:
4-Shifts-A1
4-Shifts-A0
4-Shifts-PS4
4-Shifts-A3
4-Shifts-P1
4-Shifts-PS1
4-Shifts-A4
4-Shifts-PS2
4-Shifts-A2
queries-and-tools:
4-Tool-A1
4-Tool-A5
4-Tool-P1
4-Tool-A3
4-Tool-PS1
4-Tool-A2
4-Tool-A4
4-Tool-PS2

education
building-knowledge:
5-Knowledge-P1
5-Knowledge-PS1
5-Knowledge-PS4
5-Knowledge-A3
5-Knowledge-PS2
mentorship:
5-Mentor-P1
5-Mentors-A1
5-Mentors-A4
5-Mentors-A2
5-Mentors-A0
5-Mentor-PS4
5-Mentors-V1
5-Mentors-A5
5-Mentors-A3

ripple-effect
effects-and-toll:
6-Effect_Toll-A1
6-Effect_Toll-P1
6-Effect_Toll-PS1
6-Effect_Toll-A2
6-Effect_Toll-A0
6-Effect_Toll-PS4
6-Effect_Toll-A3
6-Effect_Toll-A4
6-Effect_Toll-A5
6-Effect_Toll-PS2

intersections
gender-equality:
7-Gender-P1
7-Gender-A3
7-Gender-PS2
7-Gender-PS1
7-Gender-A2
7-Gender-A0
7-Gender-PS4
hierarchy-&-class:
7-Hierarchy-A1
7-Hierarchy-A2
7-Hierarchy-A3
7-Hierarchy-P1
7-Hierarchy-PS1
7-Hierarchy-A4
7-Hierarchy-A5
ncbs-community:
7-NCBS-P1
7-NCBS Community-A1
7-NCBS Community-A4
7-NCBS Community-A2
7-NCBS-PS1
7-NCBS-PS2
7-NCBS Community-A3

**Comment by salus-sage** [comment]
Content in each page should be displayed now, @Madhuvanthi-A  please test again and report if any issues found
