### ISSUE TITLE
Menu page: Not responsive to screen size 

### ISSUE THREAD

**Issue by vns2** [janastu/ncbs-modular#130]
Menu page should also change in size according to screen size. Not happening right now.

![menu page](https://user-images.githubusercontent.com/4581081/29065419-a287cdc2-7c49-11e7-85db-0017336d72d5.png)

**Comment by Madhuvanthi-A** [comment]
in pipeline for 1.0.2

**Comment by Madhuvanthi-A** [comment]
in pipeline, still need to consult thara about how the page should look in mobile screens

**Comment by salus-sage** [comment]
The height of the modal needs to be dynamic, right now its fixed to 100VH unit, instead should be a dynamic measuring unit like auto or 100% of the content. 
refer: bootstrap 3 documentation
