### ISSUE TITLE
Large image/audio/video icon: Not clickable

### ISSUE THREAD

**Issue by vns2** [janastu/ncbs-modular#132]
Large icons for image and audio and video are not clickable. Only shows up on Identity theme.

![large_icon](https://user-images.githubusercontent.com/4581081/29065934-57fe93f6-7c4b-11e7-8059-6082f9ddb138.png)

**Comment by Madhuvanthi-A** [comment]
this one is lined up for 1.0.3 and later

**Comment by salus-sage** [comment]
At this time it's not straight forward to implement a click on the motif's, as the content is basically the First set of image/slide and the motifs are only visual elements to block quote the featured slider, hence marking wontfix and closing this issue.
