### ISSUE TITLE
Image captions are too long, and sometimes cover the entire slideshow viewport. 

### ISSUE THREAD

**Issue by vns2** [janastu/ncbs-modular#133]
In mobile size, if you click on a slideshow icon, the caption can cover the image to a point where you cannot click through the slideshow.

The caption size should scale with the size of the screen perhaps, or it should be decoupled from the images so that all parts are clickable.

![mobilesize_slideshow](https://user-images.githubusercontent.com/4581081/29066047-b884409a-7c4b-11e7-83e8-8a654e9fe49c.png)

**Comment by Madhuvanthi-A** [comment]
i'm sorry out of scope for V1.0. 
I feel the caption is too long, this one should be marked for discussion.

**Comment by salus-sage** [comment]
currently the font size for captions is reduced as a intermediate solution.

**Comment by salus-sage** [comment]
also the thumbnails will be disabled, and this issue will be marked resolved
