### ISSUE TITLE
Audio slideshow: No scrolling text

### ISSUE THREAD

**Issue by vns2** [janastu/ncbs-modular#134]
The audio, when playing, should not have scrolling text. To make this work on all screens, I suggest that one has an icon to click to look at caption, and then, it opens up a small lightbox with the full caption. That way, caption is always visible across screen sizes.

![mobilesize_audio](https://user-images.githubusercontent.com/4581081/29066146-ff036636-7c4b-11e7-9a35-ef4e839fc1a1.png)

**Comment by Madhuvanthi-A** [comment]
we still haven't worked on a design spec for this. this will stay like this until V2.0 as per @salus-sage

**Comment by salus-sage** [comment]
what i mean is that we do not yet know how to show the captions for either Image or Audios considering the length of line varying, and other challenges related to screen sizes. 
All Labels :Design will be consulted with Thara.
