### ISSUE TITLE
Content: Remove above/below words

### ISSUE THREAD

**Issue by vns2** [janastu/ncbs-modular#136]
Text edits not taken yet - above/below words from all content to be removed as per email.

**Comment by Madhuvanthi-A** [comment]
@vns2  sorry, unable to understand this issue, need more description.
we have replaced the content as per the last email. u will provided with instructions to edit content, please hold till then on content issues.

**Comment by vns2** [comment]
---------- Forwarded message ----------
From: Venkat Srinivasan <venkat.srinivasan@gmail.com>
Date: Wed, Jul 19, 2017 at 11:04 PM
Subject: Process for text edit (above / below) in exhibit content
To: Bhanu Prakash <bhanu@servelots.com>, "Thara .M.Thomas" <tharathomas@gmail.com>


1) Find the following sentences in content under theme/chapter. 
2) Remove the words "audio", "above" and "below" and "slideshow" as highlighted from these sentences (within quotes).

Theme: Identity

Chapter: Space for Biology
"click on the audio slideshow below of MS Swaminathan, who was then at the Indian Agricultural Research Institute in Delhi."

///

Theme: Insttn Building

Chapter: Space and Autonomy
"These meeting minutes, along with a set of guidelines sent in May 1992 by Virendra Singh, then director of TIFR, can be seen in the slideshow below."

"And on a lighter note, see K VijayRaghavan’s talk below on when one of NCBS' own faculty members, KS Krishnan, decided to set up a remote marine biology laboratory."

Chapter: Paper Trails
"The TIFR Council discusses this in a June 1989 meeting -- see the slideshow above."

"The slideshow below has almost three dozen records placed in sequence, to give a flavour of the negotiations happening at the time."

Chapter: Architecture
"Have a look at the slideshow below that chronicles documents and photos from the start to end of the first phase of NCBS’ construction"

"The slideshow below gives a glimpse into the early design models, to landscaping and to early days of an aesthetic committee."

///

Theme: Growth

Chapter: Hiring
"The slideshow below shows the paper trail behind Obaid Siddiqi’s hiring, and some other hiring decisions in the decades after at TIFR’s Molecular Biology Unit (MBU) and NCBS."

Chapter: Startups
"Check out these documents in the slideshow below."

"The featured photo above and those in the slideshow below show documents and scenes from the NCBS days before it moved to the current campus."

Chapter: Scaling
"In the featured audio slideshow are some of the documents shared with a review committee."

"These notes, and other historical documents around scale, are in the slideshow below."

///

Theme: Research

Chapter: Basic/Applied Toggle
"But, as is seen in his 1945 Institute inauguration speech included in the slideshow below, it was not all black and white."
 
"See the meeting minutes from April 2000 in the slideshow below, where the faculty offer their diverse views in response to a potential collaboration with Reliance Industries." 

Chapter: Areas and shifts
"Obaid Siddiqi’s interview clip in the Gallery and Jayant Udgaonkar’s memories of that meeting shown below reflect this philosophy."

"The featured slideshow below shows records that discuss research focus in those early years at TIFR."

///

Theme: Education

Chapter: Knowledge
"These are shown in the audio slideshow below."

"Also see the documentary excerpt below on what Vidita Vaidya, a TIFR faculty member, thinks could be a good way to go beyond TIFR and extend Homi Bhabha’s legacy."

///

Theme: Ripple Effect

Chapter: Toll
"Listen to her interview excerpt and see the discussions at the 1997 TIFR review in the audio slideshow below."

"The slideshow below has meeting minutes from 1997, showing, for instance, how the institute had to settle with squatters who had built homes on land allocated to NCBS."

"Listen to her interview excerpt and see the discussions at the 1997 TIFR review in the audio slideshow below."

Chapter: Isolation
"Perhaps the cheapest metaphor to describe this perception of elitism is to look at the featured photo above of the newly constructed NCBS in 1998."

///

Theme: Intersections

Chapter: Gender
"See the slideshow below for more."

"Take a look at Veronica Rodrigues' 1990 note below in response to gender biases at TIFR, where she admonishes the Institute on their habit of addressing women by their marital status in official correspondence."

"For more, see the article excerpt below by Gaiti Hasan, an NCBS faculty member, and hear her audio excerpt comparing today’s climate to when she started her career."

Chapter: NCBS Community
"The slideshow below shows an annexure from a 1996 Project Management Committee meeting."

"Check out the slideshow below for the whole talk."

Chapter: Outside world
"Here, the general perception is that students are growing up “apolitical”, as seen in one of the images in the slideshow above."

"In the featured video below, the economist, Prabhat Patnaik, summarizes the political involvement of Obaid Siddiqi while in college in the late 1940 and early 1950s."

"The slideshow below has excerpts from that interview, one of the few where he freely shares his reflections on a leftist leaning in college, and the changes he saw in himself over time."

**Comment by salus-sage** [comment]
Adding this to pipeline after 1.0.5
