### ISSUE TITLE
Sandbox: Make consistent with rest of site: Intro chapter

### ISSUE THREAD

**Issue by vns2** [janastu/ncbs-modular#140]
Sandbox should have an intro tab. In that, all the intro text for each widget should come in -- peopleplex, timeline, spacetour, oral history, ephemera, etc. When you click on each, it just goes to the content directly without an intro always present. Ephemera click will take you back to home page to the bottom view of the home page image as we discussed. 

That way, within each tab, the content can be pushed up in the screen further, and the intro is all in one place, just like all other themes.

**Comment by Madhuvanthi-A** [comment]
Design issue, will consult with the designer.
