### ISSUE TITLE
Gallery: Not displayed in Research-Basic&Applied Toggle,RippleEffect-Interaction&Isolation, Intersections-GenderEquality.

### ISSUE THREAD

**Issue by Madhuvanthi-A** [janastu/ncbs-modular#146]

**Comment by salus-sage** [comment]
The Gallery for Toggle has only one Video element and hence the image gallery is not showing the thumbnail. Currently gallery is working only for images

**Comment by salus-sage** [comment]
@Madhuvanthi-A  please do the testing I suggested for the rest of the chapters and confirm if those galleries do not have any images.
