### ISSUE TITLE
Social media share: dropdown in progress?

### ISSUE THREAD

**Issue by vns2** [janastu/ncbs-modular#166]
Like new 'share' button on home page. Suggest moving it a little more to the left, but leave that to design view.

Clicking it results in 'blank' box opening below, see attached. I assume this is still in progress, tied to issues #113 and #114 ?

![share button](https://user-images.githubusercontent.com/4581081/29242284-a84695c0-7fa7-11e7-8346-3ed9782f395d.png)

**Comment by salus-sage** [comment]
issue resolved
