### ISSUE TITLE
Home page: view caption: bring in line with 'view' icon?

### ISSUE THREAD

**Issue by vns2** [janastu/ncbs-modular#167]
I like current view caption size. However, can it be brought into space in line with view icon? There is so much room on the right side of that view icon, it will look fitting. And I feel that way, we don't have scroll once again and there are no chances of caption getting hidden. See attached.

![homepage_view_caption](https://user-images.githubusercontent.com/4581081/29242303-188e0f52-7fa8-11e7-9583-f17111e009eb.png)

![homepage_view_caption2](https://user-images.githubusercontent.com/4581081/29242315-600484ba-7fa8-11e7-900e-b3ea2c70c91b.png)

**Comment by salus-sage** [comment]
This feature works in Firefox, have to test in chrome.

**Comment by Madhuvanthi-A** [comment]
In chrome view caption display after view icon. In Opera view caption is not displayed.
