### ISSUE TITLE
Home page: Ephemera images: credit/rights field missing

### ISSUE THREAD

**Issue by vns2** [janastu/ncbs-modular#168]
Looks like credit/rights field is missing in captions seen upon clicking 'view' below home page image.
If rights field is empty in spreadsheet, leave it blank.

**Comment by salus-sage** [comment]
didn't find credit rights field in the ephemera content.

**Comment by salus-sage** [comment]
@Madhuvanthi-A  i have sent you the excel sheet, in which 3 images have rights field, which needs to be updated in the code.
