### ISSUE TITLE
Opera: Footnote display next to last paragraph of every intro page and Sandbox.

### ISSUE THREAD

**Issue by Madhuvanthi-A** [janastu/ncbs-modular#171]
**Identity page** 
![identity](https://user-images.githubusercontent.com/21305673/29514667-f66c3422-8686-11e7-944c-4ce185478650.jpg)

**Snadbox**
![snadbox](https://user-images.githubusercontent.com/21305673/29514668-f6844d1e-8686-11e7-8b8b-898f05a2dc64.jpg)

**Comment by salus-sage** [comment]
As per our discussion, this issue is not reflected in the latest version of opera, so this issue can be marked resolved
