### ISSUE TITLE
Opera: Header style changes on refreshing the page.

### ISSUE THREAD

**Issue by Madhuvanthi-A** [janastu/ncbs-modular#172]
![header](https://user-images.githubusercontent.com/21305673/29515841-b219e5b2-868b-11e7-96f8-449332b3455e.jpg)

![header1](https://user-images.githubusercontent.com/21305673/29515840-b2172278-868b-11e7-805f-e82d9fda2591.jpg)

![header3](https://user-images.githubusercontent.com/21305673/29515843-b229561e-868b-11e7-9fb3-33f2a7649186.jpg)

![heder2](https://user-images.githubusercontent.com/21305673/29515842-b225d174-868b-11e7-969f-cd601835e73d.jpg)

**Comment by salus-sage** [comment]
as per our discussion, the latest versions of Opera is working fine. this issue  can be marked resolved
