### ISSUE TITLE
Opera: View caption is not displayed.

### ISSUE THREAD

**Issue by Madhuvanthi-A** [janastu/ncbs-modular#173]
![viewcaption](https://user-images.githubusercontent.com/21305673/29516091-aa5fa342-868c-11e7-9b27-27dfb89ac5ee.jpg)

**Comment by salus-sage** [comment]
Do you mean after click also u still can't see the caption?

**Comment by Srikavi** [comment]
Hi guys,

It has to do with cross-browser testing :)

Sri

**Comment by Madhuvanthi-A** [comment]
It displays in Windows Opera(version 47.0) but not in Ubuntu Opera(version 12.0)

**Comment by Madhuvanthi-A** [comment]
installed opera stable version in Ubuntu and the caption is displayed.

**Comment by Srikavi** [comment]
Responsive web design? Just my two cents.

Sri

**Comment by Srikavi** [comment]
How do we deal with browser versions on different operating systems? It's
what I'm wondering about!

Edit: Changed period to an exclamation at the end :)
Sri

**Comment by salus-sage** [comment]
Hi Sri Kavi,
Can you please introduce yourself?

**Comment by salus-sage** [comment]
http://caniuse.com/#search=display-contents
@Madhuvanthi-A css propert display:contents is only supported in firefox, can you please help with finding an alternative style for inline display.

**Comment by salus-sage** [comment]
@Madhuvanthi-A did you push the changes you showed me today?
