### ISSUE TITLE
Opera: Audio and Video are not playing. 

### ISSUE THREAD

**Issue by Madhuvanthi-A** [janastu/ncbs-modular#174]

**Comment by salus-sage** [comment]
Can you check html5 player browser compatibility with opera. You can Google
n see at mdn short for Mozilla Dev network documentation for the chart.

**Comment by Madhuvanthi-A** [comment]
okay.

**Comment by salus-sage** [comment]
And please update the screen shot of the chart, wid ur comments

**Comment by salus-sage** [comment]
As per our discussion, this issue is not reflected in the latest version of opera, so this issue can be marked resolved
