### ISSUE TITLE
Chrome version 17: Footnote display next to last paragraph of every intro page and Sandbox.

### ISSUE THREAD

**Issue by Madhuvanthi-A** [janastu/ncbs-modular#177]
Chrome V30 and above no issues found.

![chrome17_identity](https://user-images.githubusercontent.com/21305673/29863429-4ed67156-8d8d-11e7-913b-19249496fb8b.jpg)

![chrome 17 sandbox](https://user-images.githubusercontent.com/21305673/29863430-4ede35b2-8d8d-11e7-998b-5cff69fe3503.jpg)

**Comment by salus-sage** [comment]
can you please update more description for this test case, like what did you expect and what was the actual outcome.

**Comment by salus-sage** [comment]
In any case per pour conversation Chrome V30 and above if it's fine, then sounds good.
