### ISSUE TITLE
search button

### ISSUE THREAD

**Issue by pratiksha6656** [janastu/ncbs-modular#185]
If we click on search  button the search highlights and goes off, we cant type anything as the cursor is not available inorder to search. 

browser: chrome Version 57.11.2987.98

**Comment by salus-sage** [comment]
currently working only with keyboard tab key after clicking the search button, 
need to fix

**Comment by salus-sage** [comment]
@Madhuvanthi-A  Please read this and let me know if you didn't understand
http://www.ovais.me/javascript/bootstrap-3-dropdown-form-without-form-tag/

The event bubbling after the dropdown open is the reason, we need to stopPropagation on click event to be able to fix this issue, and also call focus method on the input element to be able to add text.
