### ISSUE TITLE
For Image 2016-TIFR-bird-graffiti.JPG there is space left in bottom of View button in Mobile 

### ISSUE THREAD

**Issue by Jabiulla24** [janastu/ncbs-modular#194]
For the image src

http://archives.ncbs.res.in/exhibit/13ways/imgs/Ephemera/2016-TIFR-bird-graffiti.JPG

there is a white space present but for other images there are no space left below View Button in Lenovo K3 Note

**Comment by salus-sage** [comment]
can you please update a screenshot for the same

**Comment by Jabiulla24** [comment]
![img_20170926_145053](https://user-images.githubusercontent.com/24510225/30853403-541432da-a2cc-11e7-9ee8-cc84faf47365.jpg)

**Comment by Jabiulla24** [comment]
There is gap in this image

**Comment by salus-sage** [comment]
can you please update your browser details

**Comment by salus-sage** [comment]
space is intentional hencce closing the issue
