### ISSUE TITLE
When clicked menu in phones the yellow background does not cover the screen so the text is not clearly visible

### ISSUE THREAD

**Issue by vaishnavisv** [janastu/ncbs-modular#195]
I have attached the screenshot how it looks on my phone.

![screenshot_2017-09-25-15-05-35](https://user-images.githubusercontent.com/24469787/30802289-9c9c1726-a203-11e7-95bf-0ae783187f5a.png)

**Comment by Madhuvanthi-A** [comment]
Can you provide mobile info(which moile and screen resolution)? Because it work fine in coolpad 1080 pixels by 1920 pixels.

**Comment by salus-sage** [comment]
and also ccan you please try to open it in your mobile browser, than the gmail browser.

**Comment by vaishnavisv** [comment]
Device Model no : Lenovo A600
Screen resolution : 720x1280
Display - 5inch


The screenshot in the browser

![screenshot_2017-09-25-16-24-32](https://user-images.githubusercontent.com/24469787/30805506-53b7e876-a20f-11e7-8937-2c6fcd9cc322.png)

**Comment by Madhuvanthi-A** [comment]
Works fine in latest version of Google chrome.
