### ISSUE TITLE
issues in safari browser 

### ISSUE THREAD

**Issue by vaishnavisv** [janastu/ncbs-modular#200]
There is a similar issue like in #195 in the safari browser 9.0 in i- phone 9.0. Screen resolution is 1080x1920 .The url for snapshot is

[(https://app.crossbrowsertesting.com/public/iffe87339650d725/livetests/9135656/snapshots/z52dc68e1c28d0f480e6)]

**Comment by salus-sage** [comment]
tested, and issue does not exist in latest version of safari
