### ISSUE TITLE
Peopleplex: all the nodes are not displaying in the phone

### ISSUE THREAD

**Issue by vaishnavisv** [janastu/ncbs-modular#208]
the screenshot of the peopleplex nodes

![screenshot_2017-10-03-16-12-10](https://user-images.githubusercontent.com/24469787/31121611-9921cd62-a856-11e7-8134-e0430d25bde3.png)

**Comment by salus-sage** [comment]
The d3 illustration cannot be supported for small devices hence an alternative browsing strategy will be rendered for hand held devices.

**Comment by salus-sage** [comment]
we'll test if this work on tablets and restrict access on small devices.

**Comment by salus-sage** [comment]
related to issue #264

**Comment by salus-sage** [comment]
Solution: using mobile-detect.js in janastu/peopleplex for disabling view rendering
