### ISSUE TITLE
Opera: Empty space in view caption for every ephemera images.

### ISSUE THREAD

**Issue by Madhuvanthi-A** [janastu/ncbs-modular#210]
![screenshot_2017-10-03_19-33-21](https://user-images.githubusercontent.com/21305673/31129418-1e146226-a872-11e7-9580-ed3a895bc6ad.png)

**Comment by Madhuvanthi-A** [comment]
display: inline-table; style is fine? I cross checked, it works fine in all browser.

**Comment by salus-sage** [comment]
Does it work for all screen sizes?
