### ISSUE TITLE
Sandbox design integration for Space Tour

### ISSUE THREAD

**Issue by vns2** [janastu/ncbs-modular#213]
Internal design for Space Tour to be aligned with rest of website. Seems to be done for all other Sandbox elements. Not sure if I see it in Space Tour though. If it is done, then I think the font sizes / bold level should match across Sandbox widgets?

**Comment by salus-sage** [comment]
also includes #244

**Comment by salus-sage** [comment]
issue resolved and pushed to server, testing in progress
