### ISSUE TITLE
Ephemera opening image: Aspect ratio responsive

### ISSUE THREAD

**Issue by vns2** [janastu/ncbs-modular#215]
The opening image on the website is responsive in width for all screens. Can it be tweaked to make it responsive in height as well. That is, one does not have to scroll down to click 'View'. The whole image shows up on screen. 

![opening_image_responsive](https://user-images.githubusercontent.com/4581081/31170952-b66427ba-a91b-11e7-8f8c-de15dbd51293.png)

**Comment by salus-sage** [comment]
There's no two diff responsive in terms of width and height. Responsive
means the image aspect ratio w*h is maintained. This cannot be addressed,
scrolling is a part of the website.

**Comment by vns2** [comment]
Ah, understood.
