### ISSUE TITLE
Sandbox: Audio overlay to be stopped

### ISSUE THREAD

**Issue by vns2** [janastu/ncbs-modular#217]
Example: If you start an audio in peopleplex and go to another sandbox widget, audio will continue playing.  Ditto for space tour or oral history. So, possible to have audio overlay across three elements. Suggest change such that when you switch to a different sandbox widget, the audio stops (the way it stops already when you switch to one of the narrative themes).

**Comment by salus-sage** [comment]
related to issue #244

**Comment by salus-sage** [comment]
This issue cannot be resolved in the current setup and architecture. As each sandbox element is a embed and ncbs-modular can't delegate events to the embeded app.,
