### ISSUE TITLE
Gallery Icons spacing

### ISSUE THREAD

**Issue by vns2** [janastu/ncbs-modular#220]
I think there should be a little more spacing (and maybe a thin horizontal line?) after the last word of the narrative text, before we have the gallery icons.

Also, personally, I feel the icons could be smaller. They are right now bigger than the main theme heading icons.

![gallery_icons_spacing](https://user-images.githubusercontent.com/4581081/31173793-8a4b8bfe-a926-11e7-97f6-e0d0e61259a7.png)

**Comment by salus-sage** [comment]
Tis is marked for tweaking with thara this week.

**Comment by salus-sage** [comment]
- [x] margin 10px

- [x] padding 5px

- [x] width 60px

- [x] Heading "Image Gallery" "Video Gallery" dont need click to open

- [x] text color dark gray like menu text
