### ISSUE TITLE
Opera: Audio is not playing. 

### ISSUE THREAD

**Issue by Madhuvanthi-A** [janastu/ncbs-modular#221]

**Comment by salus-sage** [comment]
I thought we already resolved this, can you please explain more as wot it
means for audio not playing, is there an error in the console? Or is the
player not clickable?

**Comment by salus-sage** [comment]
And also mind you there are two different audio players now, so do u mean
the inline audio html5 player or the gallery audio?

**Comment by Madhuvanthi-A** [comment]
Ya. All the audio's are not playing. Audio in gallery throws error iplayer.swf 404 page not found.
![screenshot_2017-10-04_18-36-42](https://user-images.githubusercontent.com/21305673/31177299-3792aee4-a933-11e7-819e-35056806646b.png)

**Comment by Madhuvanthi-A** [comment]
In space tour audio icon is not click able.
![screenshot_2017-10-04_18-41-02](https://user-images.githubusercontent.com/21305673/31177425-9b12fadc-a933-11e7-8f31-04a81eab40b2.png)

**Comment by Madhuvanthi-A** [comment]
No error is shown in console for inline audio html5 player.

**Comment by salus-sage** [comment]
Check your browser version and update the issue.

**Comment by Madhuvanthi-A** [comment]
latest version is 48 and mine is 47

**Comment by Madhuvanthi-A** [comment]
i will update

**Comment by salus-sage** [comment]
Update to latest version and test please.

**Comment by Madhuvanthi-A** [comment]
Works fine in 48.0.2685.35 version.

**Comment by salus-sage** [comment]
So u think this issue can be closed as resolved?

**Comment by Madhuvanthi-A** [comment]
No.Since I labelled as "bug" that's why I marked resolved. Sorry.

**Comment by salus-sage** [comment]
No problem, just close this issue with comment that no resolution needed.
