### ISSUE TITLE
Menu modal design changes

### ISSUE THREAD

**Issue by salus-sage** [janastu/ncbs-modular#228]
- [x] remove logo

- [x] left align header with About link first and then the search icon with dropdown for the input field

- [x] background color rgb(51,51,51) without opacity meaning opaque

- [x] text colors are in yellow ##FFA008 and on hover white

- [x] Vertical spacing between the blocks is not equal in small screens due to auto height.

**Comment by salus-sage** [comment]
align search link with the Institution building column

**Comment by Madhuvanthi-A** [comment]
aligned search text with respect to Institution building column.
