### ISSUE TITLE
1-space-ps2 slide order requested to be changed as per design suggestion

### ISSUE THREAD

**Issue by salus-sage** [janastu/ncbs-modular#233]
To open the slider with 1-space-ps2-2 insteatd of 1-space-ps2-1

**Comment by vns2** [comment]
This will have to be looked at on a case by case basis. 

In this particular case, 1-Space-PS2 is a chronological account of five year plan excerpts. So, the order cannot be changed. But in some other slideshows where chronology does not matter, one can investigate this possibility. Any other locations where one needs to review for design?
