### ISSUE TITLE
scroll top update new icon and cursor pointer

### ISSUE THREAD

**Issue by Madhuvanthi-A** [janastu/ncbs-modular#239]

**Comment by salus-sage** [comment]
you have changed the hover state, however `cursor:pointer` is not updated. that means the mouse pointer will change to hand when you move on the element

**Comment by Madhuvanthi-A** [comment]
Modified cursor pointer. Should I mark resolved or wait for new icon?

**Comment by salus-sage** [comment]
issue resolved
