### ISSUE TITLE
Menu Search button working?

### ISSUE THREAD

**Issue by vns2** [janastu/ncbs-modular#254]
The Menu Search button is not functional. Mayb this is already in the plan elsewhere on Git? 

![menu_search](https://user-images.githubusercontent.com/4581081/33306879-67225a56-d43a-11e7-9235-cc0b4aa1f198.png)

**Comment by salus-sage** [comment]
Yes, this is fixed but not pushed to server yet.

**Comment by vns2** [comment]
What is the general update on server pushes -- when would that be up?

**Comment by salus-sage** [comment]
We are all pretty tied up, I can't push  before testing. I ll give u the
dates shortly.

**Comment by salus-sage** [comment]
Fixed in milestone https://github.com/janastu/ncbs-modular/milestone/6
