### ISSUE TITLE
Disclaimer page closes on pressing escape key

### ISSUE THREAD

**Issue by pratiksha6656** [janastu/ncbs-modular#257]

**Comment by salus-sage** [comment]
you can try this code snippet, and then we can discuss where to implement the solution
https://stackoverflow.com/questions/24958558/bootstrap-3-modal-is-closed-when-enter-is-pressed-but-form-is-not-submitted

> ```$(document).keypress(function(e) {
>     if(e.which == 13) {
>         alert('You pressed enter!');
>     }
> });```
