### ISSUE TITLE
[correction All Links in Footer] About link at the footer: when clicked displays the bottom section of about page

### ISSUE THREAD

**Issue by pratiksha6656** [janastu/ncbs-modular#259]
From every chapters introduction section when the about link at the footer is clicked the content of the about page is displayed properly but the header of about page is hidden (we need to scroll up to see the header). 

But rest of the tabs in a particular chapter when the about link at the footer is clicked , the about page bottom section is displayed.

**Comment by salus-sage** [comment]
Bug confirmed, 
Solution is to use $(window).scrollTop() for about route or if similar conditions for any other routes.

**Comment by salus-sage** [comment]
Issue resolved
