### ISSUE TITLE
Search button not working in ipone safari

### ISSUE THREAD

**Issue by vns2** [janastu/ncbs-modular#268]
Using iOS on phone to access website. Typing something in the search option does not go to a results page. There is no 'Go' button to click, and on the laptop, one can press 'return key' to get query result. Solution might be to have a 'Go' button next to search box. Perhaps this is covered in a different issue?

**Comment by salus-sage** [comment]
In the phone keyboard also, after typing the query u can hit return key and the search should perform. it will help if you take a screenshot of keyboard layout while typing in the search form. That ll help debug this issue

**Comment by vns2** [comment]
On the phone keyboard, I type Siddiqi - shown in IMG_9152. After that, when I hit 'Done' or when I hit 'Return' key, the search gets erased and it looks like in IMG_9153.

Mobile: iPhone/iOS/Safari.
It seems to work okay on iPhone/iOS/Chrome


![search_mobile_img_9153](https://user-images.githubusercontent.com/4581081/39224678-247bfebe-4866-11e8-9659-1e126f8e2ffc.PNG)
![search_mobile_img_9152](https://user-images.githubusercontent.com/4581081/39224679-24a7a15e-4866-11e8-82c9-3a44b6ec4f1c.PNG)

**Comment by salus-sage** [comment]
changed title for Mobile: iPhone/iOS/Safari.

**Comment by salus-sage** [comment]
as far as our testing with online simulators have passed. we ll need a real device to test. 
Thanks
