### ISSUE TITLE
Audio player bug

### ISSUE THREAD

**Issue by Deepu26** [janastu/ncbs-modular#269]
Whenever i play an audio file , there will be an text popped on below to that player . The issue is whenever i close the popped up text, the audio will be stopped playing . 

![screenshot from 2018-04-16 17-33-42](https://user-images.githubusercontent.com/35370045/38808099-8723b262-419c-11e8-9899-6111f2a3f3c1.png)

**Comment by salus-sage** [comment]
This issue should be closed with label marked "won't fix", as that's the
default behaviour as planned for the audio play list. If the list is empty,
the player is empty.
