### ISSUE TITLE
Search option opening 3 new tabs

### ISSUE THREAD

**Issue by Deepu26** [janastu/ncbs-modular#270]
Whenever i open sitemap , it will open a list of options with a search option . When i search any related option in that site , then it will be opening new 3 tabs with " search 0 total " message . Please refer the screenshot 
![screenshot from 2018-04-16 17-45-09](https://user-images.githubusercontent.com/35370045/38808601-67d03e56-419e-11e8-977b-16ff90ccaa10.png)
![screenshot from 2018-04-16 17-45-14](https://user-images.githubusercontent.com/35370045/38808623-7b513e58-419e-11e8-97f8-b89147a76a28.png)

**Comment by salus-sage** [comment]
seems like the event is being called more than once. 
and happens when you use the search in header and then followed by the search in sitemap
