### ISSUE TITLE
Sandbox: Space-tour full screen mode bugs

### ISSUE THREAD

**Issue by Madhuvanthi-A** [janastu/ncbs-modular#273]
When user is in full screen mode:

- [ ] When user clicks on information and play an audio. Audio is played in background. To operate audio player, user should exit full screen mode.

![onlyaudio](https://user-images.githubusercontent.com/21305673/38869231-92b73b3c-4267-11e8-98b2-b7447e4889ff.png)

![only_audio1](https://user-images.githubusercontent.com/21305673/38869240-9b3964ba-4267-11e8-8c48-6fea5e66bc40.png)

- [ ] Both images and audio are opened in background. If user clicks first on audio then on image or first on image then on audio, when user exit full screen mode user should close image slider first then audio player. It's not like which is opened last that is appeared first. 

![audio image](https://user-images.githubusercontent.com/21305673/38869632-f8f05626-4268-11e8-9091-43cec9a5da19.png)

![audio image1](https://user-images.githubusercontent.com/21305673/38869649-033d0e62-4269-11e8-932b-b703b7edb2cf.png)

![audio image2](https://user-images.githubusercontent.com/21305673/38869664-0b6b630e-4269-11e8-8740-8e70b56f22c9.png)

**Comment by salus-sage** [comment]
this is weird bug with the the ways multiple layers are composed and embedded is conflicting. disabling full screen mode for resolving this issue. https://github.com/janastu/ncbs-space-tour/commit/acc5378d4883acf29371653c29d784996f9d70bd
