### ISSUE TITLE
Oral history page contains more whitespace

### ISSUE THREAD

**Issue by pratiksha6656** [janastu/ncbs-modular#274]
We need to scroll down (even if the page is half blank) to the bottom to click on :  | Contact us | About | Site Map

**Comment by salus-sage** [comment]
@pratiksha6656  i have assigned this issue to you for resolving. Madhu or i can help u.
The container in the Oralhistory code has an absolute height setting, which should be changed to auto.
show solution before pushing. repo janastu/oral-history
