### ISSUE TITLE
Sandbox: Peopleplex image viewer 

### ISSUE THREAD

**Issue by Madhuvanthi-A** [janastu/ncbs-modular#276]
- [x] Only when user clicks on left side of the image, image is opened in image viewer.

- [x] There is no cursor pointer

**Comment by salus-sage** [comment]
@Madhuvanthi-A i'm assigning this issue to you for resolving, please update cursor pointer for image. and as for the first point, what do you mean only when user clicks on image is opened? because that's the expecyted behaviour programmed.

**Comment by Madhuvanthi-A** [comment]
yeah, I will. For first point, when user clicks **only left side of the image**(top-left, bottom-left) , image opens. If user clicks on top/right/center or bottom-right, image doesn't open.

**Comment by Madhuvanthi-A** [comment]
This is because peopleplex visualisation  is overlapping  on image.
![peopleplex](https://user-images.githubusercontent.com/21305673/38929339-929502ca-4329-11e8-8e8a-73da2ead2926.png)

**Comment by salus-sage** [comment]
Thanks for debugging, this is the kind of in depth testing I was looking
for.

**Comment by salus-sage** [comment]
issue fixed, had to modify the graph size parameters in the code. commit log [newupdates e7c8577]
