### ISSUE TITLE
Layouts for each page

### ISSUE THREAD

**Issue by salus-sage** [janastu/ncbs-modular#37]
- [x] Identity

- [x] Institution building

- [x] Growth

- [x] Education

- [x] Research

- [x] Ripple effect

- [x] intersections

**Comment by salus-sage** [comment]
Pradeep do you think it's time to follow up with Thara again to come to office so that we can do the layouts?

**Comment by pradeepc** [comment]
Bhanu, First will show the layout what we done for so far on skype call, If she said ok then no need to come, otherwise we can call her.

**Comment by pradeepc** [comment]
Exactly !!!

**Comment by salus-sage** [comment]
Removing resolved label as designer suggests more layout corrections
