### ISSUE TITLE
#38 Videos are not playing in Chromium browser

### ISSUE THREAD

**Issue by pradeepc** [janastu/ncbs-modular#38]

**Comment by salus-sage** [comment]
@shalinia can you please assist @Madhuvanthi-A with cross browser testing, mostly to find the issue and also a possible solutions

**Comment by Madhuvanthi-A** [comment]
Video is playing in Chromium browser.

**Comment by salus-sage** [comment]
Can we please have proper report updating on cross browser testing?

**Comment by salus-sage** [comment]
The cross browser testing report to be updated in issue #45

**Comment by pradeepc** [comment]
The NCBS Server IP: 158.144.176.250 is too slow.
![ncbs-server-ping-status](https://user-images.githubusercontent.com/1224443/28785599-8041eb6e-7634-11e7-80b4-374dff4bec2c.png)

**Comment by tripToner** [comment]
Duplicate of issue #175
