### ISSUE TITLE
Identity-Reflections:Content and image is overlapped and Identity-Science-for-Biology: video and image is overlapped.

### ISSUE THREAD

**Issue by Madhuvanthi-A** [janastu/ncbs-modular#39]
![overlap_content](https://user-images.githubusercontent.com/21305673/28498853-6f7b96f6-6fc5-11e7-961f-2fb657499932.jpg)

![overlap](https://user-images.githubusercontent.com/21305673/28498872-dd18a046-6fc5-11e7-9a96-21597d1e0810.jpg)

**Comment by salus-sage** [comment]
issue resolved
