### ISSUE TITLE
Audio and Video are played simultaneously. When video is played audio should be paused automatically.

### ISSUE THREAD

**Issue by Madhuvanthi-A** [janastu/ncbs-modular#41]

**Comment by salus-sage** [comment]
Hi.. Please do not divert from the specs given for testing. I need to know what is working or not, more than enhancements and suggestions.

**Comment by salus-sage** [comment]
@Madhuvanthi-A  possibly you should find a solution for this, hence assigning this issue to you.

**Comment by salus-sage** [comment]
@Madhuvanthi-A  what is the update on this issue?

**Comment by salus-sage** [comment]
not part of original spec for design or development.
