### ISSUE TITLE
#46 write a media query for curatorial note for mobile devices 100% width

### ISSUE THREAD

**Issue by pradeepc** [janastu/ncbs-modular#46]

**Comment by salus-sage** [comment]
Hi @pradeepc  what is the status of this issue? do you need any help?

**Comment by pradeepc** [comment]
I have written media queries for width, I am not able to decrease or
increase width for the curatorial note. for checking media query whether
its working or not, so I applied background-color for that its applied.
Better you could see once.!!

**Comment by salus-sage** [comment]
Sure, tomorrow will sit with you for sometime, we ll finish things that are
stuck
