### ISSUE TITLE
#61 put title for menu, about anf search bar in the home page

### ISSUE THREAD

**Issue by pradeepc** [janastu/ncbs-modular#61]

**Comment by salus-sage** [comment]
Need more details on this issue

**Comment by pradeepc** [comment]
Hover on About,Search and Menu icons its should title for what does it for.
For ex: About icon most of the people will think it as help so when hover icon its should say the title of the icon.

**Comment by salus-sage** [comment]
Oh u mean tool tip?

**Comment by pradeepc** [comment]
yes tooltip.
