### ISSUE TITLE
#72 create light gallery slider for gallery items.

### ISSUE THREAD

**Issue by pradeepc** [janastu/ncbs-modular#72]

**Comment by salus-sage** [comment]
Use light gallery in click to dynamic mode 
like this example
http://sachinchoolur.github.io/lightGallery/demos/dynamic.html

**Comment by Madhuvanthi-A** [comment]
Completed json for identity and institution building page. Need to start for growth.

**Comment by salus-sage** [comment]
gallery commits d41bf25db050c861f09fd4ff562b5db98fe4e810
