### ISSUE TITLE
Gallery Videos are overlapping in Firefox and slow loading in chrome. 

### ISSUE THREAD

**Issue by Madhuvanthi-A** [janastu/ncbs-modular#73]
![screenshot_video](https://user-images.githubusercontent.com/21305673/28618801-5d3aeb8a-7223-11e7-87f0-7b1cb57666de.jpg)

**Comment by salus-sage** [comment]
Gallery layout needs to be done, please refer and use bootstrap. this issue's resolution will be your responsibility @Madhuvanthi-A

**Comment by salus-sage** [comment]
removed the old gallery view, replacing with new design component.
